### ISSUE TITLE
[BUG] pydantic 2.5 not support?

### ISSUE THREAD

**Issue by ciaoyizhen** [yuval9313/FastApi-RESTful#267]
**Describe the bug**
import fastapi_restfule failed

If you can generate a relevant traceback, please include it.
(.test_env) caoyizhendeMacBook-Air➜  test  ᐅ   cd /Users/caoyizhen/Documents/python代码/test ; /usr/bin/env /Users/caoyizhen/Documents/python代码/te
st/.test_env/bin/python /Users/caoyizhen/.vscode/extensions/ms-python.python-2023.22.1/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher
 50436 -- /Users/caoyizhen/Documents/python代码/test/test.py 
Traceback (most recent call last):
  File "/Users/caoyizhen/Documents/python代码/test/test.py", line 109, in <module>
    from fastapi_restful import Api, Resource
  File "/Users/caoyizhen/Documents/python代码/test/.test_env/lib/python3.9/site-packages/fastapi_restful/__init__.py", line 1, in <module>
    from .cbv_base import Api, Resource, set_responses, take_init_parameters
  File "/Users/caoyizhen/Documents/python代码/test/.test_env/lib/python3.9/site-packages/fastapi_restful/cbv_base.py", line 5, in <module>
    from .cbv import INCLUDE_INIT_PARAMS_KEY, RETURN_TYPES_FUNC_KEY, _cbv
  File "/Users/caoyizhen/Documents/python代码/test/.test_env/lib/python3.9/site-packages/fastapi_restful/cbv.py", line 11, in <module>
    from typing_inspect import is_classvar
ModuleNotFoundError: No module named 'typing_inspect'

**To Reproduce**
1. create dir  code : mkdir test
2. code: cd test   ->  python -m venv .env
3. source .env/bin/activate
4. pip install fastapi pydantic fastapi-restful
5. create a python file
6. import fastapi_restful

**Expected behavior**

code can be run

**Screenshots**

<img width="526" alt="image" src="https://github.com/yuval9313/FastApi-RESTful/assets/83450192/0174bdba-3392-4301-a2fb-c7187ddc01cc">

<img width="1430" alt="image" src="https://github.com/yuval9313/FastApi-RESTful/assets/83450192/bc511af7-7332-4824-84a3-7eb37131db3b">

**Environment:**
 - OS: macos
 - FastAPI RESTful, FastAPI, and Pydantic versions [e.g. `0.3.0`], get them with:
fastapi            0.108.0
fastapi-restful    0.5.0
pydantic           2.5.3
pydantic_core      2.14.6

```Python
from fastapi import FastAPI
from fastapi.requests import Request
from fastapi_restful import Api, Resource
from pydantic import BaseModel
import uvicorn


app = FastAPI()
api = Api(app)
class Model(BaseModel):
    name : str
    age : int
    

class Index(Resource):
    async def post(self, request:Request):
        data = await request.json()
        data = Model(**data)
        return data

api.add_resource(Index, "/index")

if __name__ == "__main__":
    uvicorn.run(app)
```

- Python version, get it with:

```bash
Python 3.9.6
```

**Additional context**

**Comment by ciaoyizhen** [comment]
when I  pip install typing-inspect then error message TypeError: can't set attributes of built-in/extension type 'type'
<img width="1376" alt="image" src="https://github.com/yuval9313/FastApi-RESTful/assets/83450192/9dec7eb3-d4c4-4324-9b8c-c19c4f79607a">

**Comment by ciaoyizhen** [comment]
Sorry I forgot to instantiate my Resource
